{ domain: null,
  _events: 
   { finish: [ [Function], [Function: onevent] ],
     end: [Function: onevent] },
  _maxListeners: 10,
  output: [],
  outputEncodings: [],
  writable: true,
  _last: false,
  chunkedEncoding: false,
  shouldKeepAlive: true,
  useChunkedEncodingByDefault: true,
  sendDate: true,
  _headerSent: false,
  _header: '',
  _hasBody: true,
  _trailer: '',
  finished: false,
  _hangupClose: false,
  socket: 
   { _connecting: false,
     _handle: 
      { fd: 28,
        writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread],
        reading: true },
     _readableState: 
      { highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: false,
        endEmitted: false,
        reading: true,
        calledRead: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        drain: [Object],
        timeout: [Function],
        error: [Object],
        close: [Object] },
     _maxListeners: 10,
     _writableState: 
      { highWaterMark: 16384,
        objectMode: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [] },
     writable: true,
     allowHalfOpen: true,
     onend: [Function],
     destroyed: false,
     errorEmitted: false,
     bytesRead: 4424,
     _bytesDispatched: 1292,
     _pendingData: null,
     _pendingEncoding: '',
     server: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _connections: 6,
        connections: [Getter/Setter],
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        allowHalfOpen: true,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _connectionKey: '4:0.0.0.0:10001' },
     _idleTimeout: 120000,
     _idleNext: 
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        onend: [Function],
        destroyed: false,
        errorEmitted: false,
        bytesRead: 718,
        _bytesDispatched: 281,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: 1423577695595,
        parser: [Object],
        ondata: [Function],
        _paused: false,
        _httpMessage: null,
        _peername: [Object] },
     _idlePrev: { _idleNext: [Circular], _idlePrev: [Object] },
     _idleStart: 1423577702384,
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Circular],
        incoming: [Object],
        maxHeaderPairs: 2000,
        onIncoming: [Function] },
     ondata: [Function],
     _paused: false,
     _httpMessage: [Circular],
     _peername: { address: '127.0.0.1', family: 'IPv4', port: 57835 } },
  connection: 
   { _connecting: false,
     _handle: 
      { fd: 28,
        writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread],
        reading: true },
     _readableState: 
      { highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: false,
        endEmitted: false,
        reading: true,
        calledRead: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        drain: [Object],
        timeout: [Function],
        error: [Object],
        close: [Object] },
     _maxListeners: 10,
     _writableState: 
      { highWaterMark: 16384,
        objectMode: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [] },
     writable: true,
     allowHalfOpen: true,
     onend: [Function],
     destroyed: false,
     errorEmitted: false,
     bytesRead: 4424,
     _bytesDispatched: 1292,
     _pendingData: null,
     _pendingEncoding: '',
     server: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _connections: 6,
        connections: [Getter/Setter],
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        allowHalfOpen: true,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _connectionKey: '4:0.0.0.0:10001' },
     _idleTimeout: 120000,
     _idleNext: 
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        onend: [Function],
        destroyed: false,
        errorEmitted: false,
        bytesRead: 718,
        _bytesDispatched: 281,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Circular],
        _idleStart: 1423577695595,
        parser: [Object],
        ondata: [Function],
        _paused: false,
        _httpMessage: null,
        _peername: [Object] },
     _idlePrev: { _idleNext: [Circular], _idlePrev: [Object] },
     _idleStart: 1423577702384,
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Circular],
        incoming: [Object],
        maxHeaderPairs: 2000,
        onIncoming: [Function] },
     ondata: [Function],
     _paused: false,
     _httpMessage: [Circular],
     _peername: { address: '127.0.0.1', family: 'IPv4', port: 57835 } },
  _headers: { 'x-powered-by': 'Express', vary: 'X-HTTP-Method-Override' },
  _headerNames: { 'x-powered-by': 'X-Powered-By', vary: 'Vary' },
  req: 
   { _readableState: 
      { highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: true,
        endEmitted: true,
        reading: false,
        calledRead: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: { readable: [Function] },
     _maxListeners: 10,
     socket: 
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        onend: [Function],
        destroyed: false,
        errorEmitted: false,
        bytesRead: 4424,
        _bytesDispatched: 1292,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 1423577702384,
        parser: [Object],
        ondata: [Function],
        _paused: false,
        _httpMessage: [Circular],
        _peername: [Object] },
     connection: 
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        onend: [Function],
        destroyed: false,
        errorEmitted: false,
        bytesRead: 4424,
        _bytesDispatched: 1292,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 1423577702384,
        parser: [Object],
        ondata: [Function],
        _paused: false,
        _httpMessage: [Circular],
        _peername: [Object] },
     httpVersion: '1.1',
     complete: true,
     headers: 
      { host: 'localhost:10001',
        connection: 'keep-alive',
        'content-length': '204',
        accept: '*/*',
        origin: 'http://localhost:10001',
        'x-requested-with': 'XMLHttpRequest',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        referer: 'http://localhost:10001/admin/single?id=54bd0c66849aea34125cc984',
        'accept-encoding': 'gzip, deflate',
        'accept-language': 'zh-CN,zh;q=0.8,en;q=0.6',
        cookie: 'cystudio_1=s%3AF-1qviK-X5iBcvuR9WL2Ai7JjwwCHDxn.U8pWu9rNuoJqMAwSOG%2FZVMpIuJjIPXQhP%2FDz5N1Gslo; cystudio_2=s%3AAo3SjJTa4xMFTR5KEp2jZ5x6hXRpx3Dg.bt19PcV%2BZC3yTtfxNi73GFTl%2F5s8v4sIFRu8gPahF%2BM' },
     trailers: {},
     _pendings: [],
     _pendingIndex: 0,
     url: '/mod/upload',
     method: 'POST',
     statusCode: null,
     client: 
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        onend: [Function],
        destroyed: false,
        errorEmitted: false,
        bytesRead: 4424,
        _bytesDispatched: 1292,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 1423577702384,
        parser: [Object],
        ondata: [Function],
        _paused: false,
        _httpMessage: [Circular],
        _peername: [Object] },
     _consuming: true,
     _dumped: false,
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     upgrade: false,
     originalUrl: '/mod/upload',
     _parsedUrl: 
      { protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: null,
        query: null,
        pathname: '/mod/upload',
        path: '/mod/upload',
        href: '/mod/upload',
        _raw: '/mod/upload' },
     query: {},
     res: [Circular],
     next: [Function: next],
     flash: [Function: _flash],
     _startAt: [ 161646, 618319146 ],
     _startTime: Tue Feb 10 2015 22:15:02 GMT+0800 (CST),
     _remoteAddress: '127.0.0.1',
     body: { '{"files":{"0":{"webkitRelativePath":"","lastModified":1421799831000,"lastModifiedDate":"2015-01-21T00:23:51.000Z","name":"qrcode_for_gh_89284a8fabf6_430.jpg","type":"image/jpeg","size":40319},"length":1}}': '' },
     _body: true,
     pipe: [Function],
     addListener: [Function],
     on: [Function],
     pause: [Function],
     resume: [Function],
     read: [Function],
     originalMethod: 'POST',
     secret: undefined,
     cookies: 
      { cystudio_1: 's:F-1qviK-X5iBcvuR9WL2Ai7JjwwCHDxn.U8pWu9rNuoJqMAwSOG/ZVMpIuJjIPXQhP/Dz5N1Gslo',
        cystudio_2: 's:Ao3SjJTa4xMFTR5KEp2jZ5x6hXRpx3Dg.bt19PcV+ZC3yTtfxNi73GFTl/5s8v4sIFRu8gPahF+M' },
     signedCookies: {},
     _parsedOriginalUrl: 
      { protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: null,
        query: null,
        pathname: '/mod/upload',
        path: '/mod/upload',
        href: '/mod/upload',
        _raw: '/mod/upload' },
     sessionStore: 
      { db: [Object],
        db_collection_name: 'sessions',
        _serialize_session: [Function: stringify],
        _unserialize_session: [Function: parse],
        _get_collection: [Function],
        _open_database: [Function],
        defaultExpirationTime: 1209600000,
        generate: [Function],
        _events: [Object],
        collection: [Object] },
     sessionID: 'Ao3SjJTa4xMFTR5KEp2jZ5x6hXRpx3Dg',
     session: 
      { cookie: [Object],
        flash: {},
        user: '526450935@qq.com',
        weixin: '',
        token: '2037041341',
        email: '526450935@qq.com' },
     _route_index: 23,
     route: 
      { path: '/mod/upload',
        method: 'post',
        callbacks: [Object],
        keys: [],
        regexp: /^\/mod\/upload\/?$/i,
        params: [] },
     params: [] },
  locals: [Function: locals],
  __onFinished: { [Function: listener] queue: [ [Function: logRequest] ] },
  writeHead: [Function: writeHead],
  end: [Function: end] }